### ISSUE TITLE
Many elements do not render correctly

### ISSUE THREAD

**Issue by yo1995** [IBM-Swift/Kitura-Markdown#25]
Some image tags as well as the table are not rendered correctly.  
Will these be fixed by updating the `CCMark` dependencies?

**Comment by ianpartridge** [comment]
We're very happy to update CCMark if necessary. Can you provide an example markdown that shows the problem?

**Comment by yo1995** [comment]
> We're very happy to update CCMark if necessary. Can you provide an example markdown that shows the problem?

Hi,

- Tables: from https://guides.github.com/features/mastering-markdown/

First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

```markdown
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column
```

- Img: (general image tags work fine)
![Swift](https://img.shields.io/badge/Swift-5.1-orange.svg?style=flat) 
```markdown
![Swift](https://img.shields.io/badge/Swift-5.1-orange.svg?style=flat) 
```

- checklist:
- [x] More to find in the app!

```markdown
- [x] More to find in the app!
```

---

I'm not sure which of these are generally supported by markdown, but it would be great to have them! 😃 

Also, I found emoji's not correctly displayed in my markdown rendered page. I wonder if the `<meta charset="UTF-8">` is handled by the render engine?

Really appreciated!

**Comment by ianpartridge** [comment]
GitHub markdown is a superset of CommonMark.  See https://github.github.com/gfm/ for the specification - the items you've identified are GitHub specific extensions so we can't support them here.

The issue of emoji's not rendering correctly sounds like a different issue.  Are you outputting the emoji as Unicode codepoints, or using the `:shortcode:` syntax that GitHub supports?

**Comment by yo1995** [comment]
> GitHub markdown is a superset of CommonMark. See https://github.github.com/gfm/ for the specification - the items you've identified are GitHub specific extensions so we can't support them here.
> 
> The issue of emoji's not rendering correctly sounds like a different issue. Are you outputting the emoji as Unicode codepoints, or using the `:shortcode:` syntax that GitHub supports?

Thanks for your heads up! Sorry for that I overlooked the [original specs](https://spec.commonmark.org/) for cmark 😅 . 

Talking about emoji, I'm inserting Unicode characters directly. like this: `🤔` -> 🤔, rather than using shortcode  `:thinking:` -> 🤔 or codepoints  `&#x1F914` -> 
<p>&#x1F914</p>

When I want to directly insert an emoji character, I have to specify the `charset` attribute in my markdown `.md` document. 

While it's OK to add a few lines of HTML to `.md` file, it would be great if I can set that with template engine's attribute somehow.

Currently it looks like this without setting the charset.  
![e](https://user-images.githubusercontent.com/9660181/59933369-56a01080-9417-11e9-940a-d9d1e2dece3f.png)

And it looks like this with setting charset and stylesheet with HTML tags in the `.md` file.
![f](https://user-images.githubusercontent.com/9660181/59933633-da59fd00-9417-11e9-8bcd-006926d4d065.png)

**Comment by ianpartridge** [comment]
Can you show me what you're having to put in the `.md` file to get the emoji to render properly?

**Comment by yo1995** [comment]
> Can you show me what you're having to put in the `.md` file to get the emoji to render properly?

I'm including an HTML attribute in the `.md` file to specify its charset.
```html
<head>
    <meta charset="UTF-8">
</head>
```
Without this, it seems the page defaults to some other charset, hence characters other than English cannot be displayed correctly.

**Comment by ianpartridge** [comment]
Hi, by default Kitura-Markdown doesn't generate complete HTML documents - it generates an HTML fragment.

For example, for this Markdown:

```markdown
# Header

Description with **bold** text

* Book1
* Book2
```

it will generate this HTML fragment:

```html
<h1>Header</h1>
<p>Description with <strong>bold</strong> text</p>
<ul>
<li>Book1</li>
<li>Book2</li>
</ul>
```

What you want is a complete HTML document with a `DOCTYPE` etc. so you can specify the UTF-8 character set.

There are two ways to do this.

1.  Use [`render(from: String, pageTemplate: String)`](https://ibm-swift.github.io/Kitura-Markdown/Classes/KituraMarkdown.html#/s:14KituraMarkdownAAC6renderS2S4from_tFZ) which allows you to pass in a `pageTemplate` which specifies where in the template the Markdown should be inserted.

2.  Use [`MarkdownOptions`](https://ibm-swift.github.io/Kitura-Markdown/Structs/MarkdownOptions.html) to specify a page template.

Either of these are good options and should work.

We're going to update our Markdown guide on kitura.io to make this clearer.  Thanks for raising the bug and do reopen if you have any more questions.  Thanks.

**Comment by yo1995** [comment]
Thanks for the clarification! It works!
